#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
echo "my dotfiles $DOTFILES"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    pwd
    echo "stow $folder"
    stow -D -v $folder
    stow -vt ~ $folder
done
popd
